# Generated by Django 3.1.5 on 2021-03-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
